### ISSUE TITLE
Svg icon without html div code

### ISSUE THREAD

**Issue by brian-schmidt** [iatkin/leaflet-svgicon#1]
Hi, is there any way to create a svg marker but only de <svg> tag?  to make it all within a single pane **leaflet-pane leaflet-overlay-pane** ?

for example:

![captura](https://cloud.githubusercontent.com/assets/4703377/19609869/0198ab62-97b0-11e6-86c7-9b2740130e82.PNG)

I want use  **L.marker.svgMarker(latlng)** but all the pliygon and markers in one svg tag to export later to .svg file. 

Sorry for my english.

Thank you so much!

**Comment by brian-schmidt** [comment]
I need to export all data in map to a single .svg file, then open it and manipulate it with illustrator. Please help!

**Comment by iatkin** [comment]
If you want just the SVG, use the _createSVG method of L.DivIcon.SVGIcon instead of the marker class which is specifically for map placement.

**Comment by brian-schmidt** [comment]
what I need is to change the values ​​of these svg markers to be dynamic. the data comes from a file .json thanks for your answer

**Comment by iatkin** [comment]
Are you basically trying to place the polygons and markers on a Leaflet map and then exporting that to SVG somehow? I don't think that's actually possible. You need to use a piece of GIS software to do that.
