### ISSUE TITLE
circle not anchored correctly with  custom iconSize

### ISSUE THREAD

**Issue by simon1tan** [iatkin/leaflet-svgicon#15]
Changed iconSize to [48,48] and creates a marker where the circle is offset to the left. Circle should stay centered. When I manually set the circleAnchor to [24,24], the circle is centered correctly.

**Comment by iatkin** [comment]
What version of Leaflet are you using and what browser? The code sets the circleAnchor to iconSize/2 if one is not provided.

**Comment by iatkin** [comment]
Hi. I'm closing this issue because I've been unable to reproduce it with any size icon.
