### ISSUE TITLE
unable to setStyle on marker that is not within view

### ISSUE THREAD

**Issue by simon1tan** [iatkin/leaflet-svgicon#16]
I'm trying to setStyle a marker that has moved out of view and it does not work. Once the marker is in view, I can setStyle and the marker is is styled correctly. Is there a way around this?

**Comment by iatkin** [comment]
Just for completeness, what version of Leaflet are you using and what browser? I suspect that Leaflet versions more recent than the one I used have changed some behavior as I was perfectly able to restyle markers that were out of view.

**Comment by iatkin** [comment]
Hi I am also unable to reproduce this bug. It works without issue on Leaflet 0.7 and 1.4.0.
