### ISSUE TITLE
performance issue too much markers

### ISSUE THREAD

**Issue by atadnmz** [iatkin/leaflet-svgicon#19]
Hi I was trying to handle over 30k  markers, however it runs too slow even 1k markers. Is there any way to handle this problem. btw I have added my custom .svg to your library which I need to use and tried to use them.

**Comment by iatkin** [comment]
There isn't a whole lot I can do. SVG processing is completely hardware dependent. The marker that comes with the library is fairly simply and 1k markers isn't an issue even on decade old hardware. For 30k markers, an image marker is probably a better bet as the processing requirements are significantly lower although 30k might still be a struggle for some systems.
