### ISSUE TITLE
Fill color not applied on setStyle

### ISSUE THREAD

**Issue by FabioWanner** [iatkin/leaflet-svgicon#20]
Currently the fill color is set to be the same as the color when calling setStyle

`
var fill = style.color.replace(...
`

Using `style.fillColor` should solve this issue.

**Comment by iatkin** [comment]
Hi. As noted in the documentation, the top level "color" option is for monochromatic changes. If you want to change the fill color only, use "iconOptions.fillColor".

**Comment by FabioWanner** [comment]
Hey! Thank you for your reply! Feels a bit "unintuitive" but it works! Thank you!
