### ISSUE TITLE
wrong marker text

### ISSUE THREAD

**Issue by blackgis** [iatkin/leaflet-svgicon#21]
L.marker.svgMarker is correct not that writing on your page - newest leaflet

**Comment by iatkin** [comment]
Hi. I'm not sure exactly what you mean.

**Comment by blackgis** [comment]
Hi you write 
`var marker = new L.Marker.SVGMarker(latlng, { iconOptions: { color: "rgb(0,0,100)" }})`

but it should be 
`var marker = new L.marker.svgMarker(latlng, { iconOptions: { color: "rgb(0,0,100)" }})`

**Comment by iatkin** [comment]
The first version with the "new" keyword and capitalization is the correct usage. The second is a "factory" function that returns a new object and does not require the use of the "new" keyword i.e. 
`var marker = L.marker.svgMarker(latlng)`
This is the correct usage of this method.

It is an odd quirk of Javascript that functions that return an object can have the "new" keyword prepended without issue. This is not standard behavior in other languages and should not be used even though it does technically work here. It is also standard in Leaflet to have a factory function with that type of capitalize scheme.
