### ISSUE TITLE
the fontColor option does not work

### ISSUE THREAD

**Issue by stan1870** [iatkin/leaflet-svgicon#24]
Hi and thank you so much for this tool smart and powerfull !
I use :
new L.Marker.SVGMarker([item[1],item[2]], { iconOptions: { color: "rgb(0,148,255)", fillOpacity : 1, circleText : "01", fontColor : "rgb(0,0,0)"}});
All great but the text is still in white
Regards !

**Comment by stan1870** [comment]
On chrome
leaflet version 1.5.1

**Comment by iatkin** [comment]
Hi. The fontColor option works without issue for me. What color are you getting? You specified black for the color option, but the text of your comment says white.

**Comment by iatkin** [comment]
Closed for lack of information and due to working on the platform mentioned in the issue.
