### ISSUE TITLE
How to add an icon shadow?

### ISSUE THREAD

**Issue by just-Addict** [iatkin/leaflet-svgicon#25]
Hi, I've been using your version because I discovered by accident it was the only way I currently know of to give each marker a unique ID, something I very much needed in my little homemade project.

I would however like to beautify this project a little and wanted to use a shadowed icon like in the default Leaflet tutorials. 

I've been looking at this six ways from Sunday but so far have failed in my attempts to actually get something decent looking as there doesn't seem to be a way to accomplish this when using a `L.Marker.SVGMarker`

Would appreciate any pointers you can give me. As long as I don't lose the option of having markers with unique ID's

**Comment by iatkin** [comment]
I've added basic support for shadows which will work with custom icons if their outer shape is created using the _createPathDescription method as the example subclasses are. It's a little tricky to add a proper shadow in a generic way if the bottom of the icon isn't a tip, but it should work with anything that is without modification. The example/demo has been updated with the new options.

**Comment by just-Addict** [comment]
thank you very much, I'll try it out,  May need to rework my icons as they're not exactly simple shapes and currently get loaded from external files
