### ISSUE TITLE
Dependency to src (simple redis cache)

### ISSUE THREAD

**Issue by arusa** [iatkin/leaflet-svgicon#28]
Hi, I'm really confused. I'm working with software that includes the "leaflet-svgicon" npm package. This package has a dependency to "src" (simple redis cache) according to https://www.npmjs.com/package/leaflet-svgicon 
I really don't see a reason why this dependency exists and the repo here and the older forked repo npmjs.com is linking to don't have a package.json file.
My problem is that "src" has a dependency to underscore ~1.6.0 which has an "Arbitrary Code Execution" vulnerability.

It looks like you didn't even push your library to npmjs.com, but someone who forked your github repo?

https://github.com/geemodev/leaflet-svgicon

**Comment by iatkin** [comment]
Someone seems to have squatted on the package on NPM without my knowledge. This library has no dependencies except to Leaflet. All I can suggest is to not use the version on NPM and to write your own package file if you need one.

**Comment by iatkin** [comment]
I added in a simple package.json file that you can use. I'm not very familiar with NPM so let me know if there's any issues with the file.
