### ISSUE TITLE
Update Text of Marker

### ISSUE THREAD

**Issue by pkolmann** [iatkin/leaflet-svgicon#30]
Hi,

I need to update the text of the marker via JavaScript. Has anyone achieved this already without removing the marker and recreating a new one?

**Comment by iatkin** [comment]
I'll take a look at your pull request, but my understanding is that the "correct" way is use L.Marker's setIcon with a new Icon object. There are some slightly clunky ways to reuse a Marker's existing Icon but those rely on knowing the implementation details of the Icon.

For this one, you can do something along the lines of 

`marker.options.icon.options.circleText = "newText"`
`marker.options.icon.options.html = marker.options.icon._createSVG()`
`marker.setIcon(marker.options.icon)`

Not very straightforward! An actual marker method to change the text would be better.
