### ISSUE TITLE
Suggestion to make nicer shaped markers

### ISSUE THREAD

**Issue by Joppla** [iatkin/leaflet-svgicon#4]
With the following code the marker looks nicer (the left and right line are double curved) in my opinion:
```
    _createPathDescription: function() {
        var height = Number(this.options.iconSize.y)
        var width = Number(this.options.iconSize.x)
        var weight = Number(this.options.weight)
        var margin = weight / 2

        var startPoint = "M " + margin + " " + (width/2) + " "
        var leftLine = "C " + margin + " " + width + " " + (width/2) + " " + width + " " + (width/2) + " " + (height - weight) + " "
        var rightLine = "C " + (width/2) + " " + width + " " + (width - margin) + " " + (width) + " " + (width - margin) + " " + (width/2) + " "
        var arc = "A " + (width/4) + " " + (width/4) + " 0 0 0 " + margin + " " + (width/2) + " Z"

        var d = startPoint + leftLine + rightLine + arc

        return d
    }
```
![afbeelding](https://cloud.githubusercontent.com/assets/25467829/24060538/f339aeb4-0b53-11e7-99ff-4f3a2388c660.png)

**Comment by iatkin** [comment]
I would prefer to leave the default shape as is. If you would like to include this icon shape in the repository, please create a subclass in a single file and put in the subclass directory. I just reorganized slightly and changed the subclass-examples.js file to a directory. Take a look at the the ones already there and follow that format. There should be 4 parts: the main SVGIcon subclass, a factory method for the icon, a marker class that acts as a wrapper for the icon and a factory method for the marker.
