### ISSUE TITLE
Icon fails to draw when iconSize is set

### ISSUE THREAD

**Issue by marsmith** [iatkin/leaflet-svgicon#6]
All other options seem to work fine, but if I set the `iconSize: [32,48]` as per the default, I get these errors in the console:
![image](https://user-images.githubusercontent.com/6529123/29941502-d0737ca8-8e60-11e7-9ca2-c998fdd16ab6.png)

here is a [jsfiddle](http://jsfiddle.net/25nwtort/) (switch the commented out marker to see that one work fine)

**Comment by iatkin** [comment]
I have updated the class to support Point options that are passed as arrays rather than L.Point objects. Everything should be working fine now.  It'll also work as is if you do `L.point([x,y])` instead.
