### ISSUE TITLE
SVGIcon behaves different from standard markers (mouse out etc.)

### ISSUE THREAD

**Issue by amenk** [iatkin/leaflet-svgicon#9]
QuickFix is:

    .svg-icon svg {
        pointer-events: none !important;
    }

**Comment by iatkin** [comment]
Can you be more specific about what the problem actually is? There was a small "issue" with the wrong cursor being display in Edge and Firefox due to incorrect SVG parsing in those browers (the SVG element itself was being made too big). Is this related to that or is it something else?

**Comment by amenk** [comment]
I recently replaced the standard markers by svgicon in an application where I attached mouseout events to the markers.  This is where I noticed that those stopped working. 


Just wanted to document this for others and maybe or makes sense to include the above CSS by default

**Comment by iatkin** [comment]
I'll take a look into why something like that is happening when I get a chance. There shouldn't be any different behavior from the default marker. Is this something that happens in all browsers?

**Comment by amenk** [comment]
I only tested chrome

**Comment by Stefdv** [comment]
draggable:true is not working ?

**Comment by iatkin** [comment]
Sorry for the delay.

**Comment by iatkin** [comment]
I was never able to reproduce this issue and mostly likely was due to a bug in Chrome which seems to have been fixed.
